name: cc

on:
  push:
    branches:
      -  main
      
pull_request:
    branches:
      -  main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: install Arm cross compiler
      run: sudo apt-get update
      
    - name: install Arm cross compiler
      run: sudo apt install --yes {gcc,binutils}-arm-linux-gnueabihf 
       
    - name: compile code
      run: arm-linux-gnueabihf-gcc -o out.exe helloworld.c
